[package]
name = "common-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { git = "https://github.com/golemcloud/reqwest", branch = "update-jun-2024", features = ["json"] }
serde = { version = "1.0.226", features = ["derive"] }
serde_json = "1.0.143"