package golem-ai: worker;

interface golem-ai-worker-api {
  record history-entry {
    message: string,
    response: string
  }

  ask: func(message: string) -> result<string, string>;

  history: func() -> list<history-entry>;
}

world golem-ai-worker {
  export golem-ai-worker-api;
}
